workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        BUILD_MODE: release
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --$BUILD_MODE
    artifacts:
      - build/app/outputs/flutter-apk/app-*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
